# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- newversion
- master

strategy:
  matrix:
    Russia:
      CountryName: 'russia'
    Aurora:
      CountryName: 'aurora'
    France:
      CountryName: 'france'
    Switzerland:
      CountryName: 'switzerland'


pool:
  vmImage: 'ubuntu-16.04'
  name: Azure Pipelines
  demands: npm

steps:
- powershell: |
   Get-ChildItem -Include environment.ts
   $text= Get-Content -Path "/home/vsts/work/1/s/src/environments/environment.ts"
   $text=$text -replace 'http://63.33.46.20:8080','https://$(CountryName)-springboot.azurewebsites.net' | Set-Content '/home/vsts/work/1/s/src/environments/environment.ts'
   "Propriedades> "+$text
  displayName: 'PowerShell Script'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Npm@1
  displayName: 'npm install copy'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build --prod'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/ygroup.zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: $(CountryName)-drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    artifactName: beacon-$(CountryName)
  condition: succeededOrFailed()

